services:
  sd-server:
    build: .
    image: ghcr.io/dontdrinkandroot/stable-diffusion-cpp.docker:latest
    ports:
      - "1234:1234"
    volumes:
      - models:/models
      - loras:/loras
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      - DIFFUSION_MODEL_URL=${DIFFUSION_MODEL_URL:-}
      - VAE_URL=${VAE_URL:-}
      - LLM_URL=${LLM_URL:-}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  models:
  loras:
