services:
  flux-klein-9b:
    build: .
    image: ghcr.io/philipsorst/sdcpp-flux-klein-9b.docker:latest
    ports:
      - "1234:1234"
    volumes:
      - models:/models
      - loras:/loras
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
      # - DIFFUSION_MODEL_URL=https://huggingface.co/unsloth/FLUX.2-klein-9B-GGUF/resolve/main/flux-2-klein-9b-Q6_K.gguf
      # - VAE_URL=https://huggingface.co/black-forest-labs/FLUX.2-dev/resolve/main/ae.safetensors
      # - LLM_URL=https://huggingface.co/unsloth/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q6_K.gguf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  models:
  loras:
